---
stages:
  - static analysis
  - kubectl version

.lint:
  stage: static analysis
  except:
    - tags

yamllint:
  extends: .lint
  image: orginux/yamllint:1.25.0
  script:
    - find -type f -name '*.yml' -o -name '*.yaml' -exec yamllint {} \;

kubeval:
  extends: .lint
  image: orginux/kubeval
  script:
    - ls -l gitlab-integration/test-deploy/
    - kubeval gitlab-integration/test-deploy/deploy.yaml

kube-score:
  extends: .lint
  image: zegl/kube-score
  script:
    - kube-score gitlab-integration/test-deploy/deploy.yaml

get version:
  stage: kubectl version
  image: traherom/kustomize-docker
  before_script:
    - echo $KUBECONFIG
  script:
    - kubectl apply -f gitlab-integration/test-deploy/
    - kubectl rollout status deployments/test-integration --timeout=30s
    - kubectl wait
        --file gitlab-integration/test-deploy/deploy.yaml
        --for condition=available
  after_script:
    - kubectl get deployments
    - kubectl get pod
    - kubectl get svc
  tags:
    - kubernetes
  environment:
    name: staging
    url: http://35.228.94.49
