---
stages:
  - static analysis
  - kubectl version

yamllint:
  stage: static analysis
  image: orginux/yamllint:1.25.0
  script:
    - find -type f -name '*.yml' -o -name '*.yaml' -exec yamllint {} \;
  except:
    - tags

get version:
  stage: kubectl version
  image: traherom/kustomize-docker
  before_script:
     - echo $KUBECONFIG
  script:
     - kubectl get all
  tags:
    - kubernetes
