---
stages:
  - static analysis
  - kubectl version

yamllint:
  stage: static analysis
  image: orginux/yamllint:1.25.0
  script:
    - find -type f -name '*.yml' -o -name '*.yaml' -exec yamllint {} \;
  except:
    - tags

get version:
  stage: kubectl version
  image: traherom/kustomize-docker
  before_script:
    - echo $KUBECONFIG
  script:
    - kubectl apply -f gitlab-integration/test-deploy/
    - kubectl rollout status deployments/test-integration
    - kubectl wait -f gitlab-integration/test-deploy/deploy.yaml --for condition=available
  after_script:
    - kubectl get deployments
    - kubectl get pod
    - kubectl get svc
  tags:
    - kubernetes
  environment:
    name: staging
    url: http://35.228.94.49
