stages:
  - test

test:
  image: traherom/kustomize-docker
  stage: test
  script:
    - kubectl create deployment $DEPLOY_NAME --image=orginux/echopod
    - kubectl scale deployment $DEPLOY_NAME --replicas=5
  environment:
    name: staging
  tags:
    - kubernetes
