---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: required-pod-affinity
  name: required-pod-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: required-pod-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: required-pod-affinity
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["cache"]
              topologyKey: kubernetes.io/hostname
      containers:
        - image: orginux/pod-info
          name: pod-info
          resources: {}
status: {}
