---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fileshare
spec:
  rules:
    - host: master1
      http:
        paths:
          - backend:
              serviceName: fileshare
              servicePort: 80
