---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-integration
  name: test-integration-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-integration
  type: LoadBalancer
status:
  loadBalancer: {}
