---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-hostname
spec:
  selector:
    matchLabels:
      app: container-hostname
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: container-hostname
    spec:
      containers:
        - name: hostname
          image: orginux/container-hostname:1.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: container-hostname
spec:
  selector:
    app: container-hostname
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
