---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
    environment: staging
    version: v1.0
  name: demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
        pod: tmp
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - image: orginux/pod-info
          name: pod-info
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources: {}
status: {}
