---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-integration
  name: test-integration
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-integration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-integration
    spec:
      containers:
        - image: orginux/echopod:1.2
          name: echopod
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 7Mi
              cpu: 25m
            limits:
              cpu: 25m
              memory: 10Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
status: {}
