---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-integration
  name: test-integration
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-integration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-integration
    spec:
      containers:
      - image: orginux/echopod
        name: echopod
        resources:
          limits:
            cpu: 25m
            memory: 10Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
status: {}
