---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: required-affinity
  name: required-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: required-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: required-affinity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "failure-domain.beta.kubernetes.io/region"
                    operator: In
                    values: ["europe-north1"]
      containers:
        - image: orginux/pod-info
          name: pod-info
          resources: {}
status: {}
