---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hpa-deploy
  name: hpa-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hpa-deploy
    spec:
      containers:
        - image: orginux/echopod
          name: echopod
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 100m
status: {}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-deploy
  labels:
    app: hpa-deploy
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hpa-deploy
