---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: demo-np-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-np
  name: deploy-np
  namespace: demo-np-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-np
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-np
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-np
  name: deploy-np
  namespace: demo-np-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30008
  selector:
    app: deploy-np
  type: NodePort
status:
  loadBalancer: {}
...
