---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-np
  name: deploy-np
  namespace: np-service-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: deploy-np
  type: NodePort
status:
  loadBalancer: {}
